name: Update GameLove Hosts

on:
  schedule:
    # 每小时自动更新一次
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      force_update:
        description: '强制更新'
        required: false
        default: 'false'
        type: boolean

jobs:
  update-hosts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 生成 hosts 文件
      run: |
        cd scripts
        python update_hosts.py
    
    - name: 检查是否有更新
      id: check_changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "发现文件变更"
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "没有文件变更"
        fi
    
    - name: 提交更新
      if: steps.check_changes.outputs.has_changes == 'true' || github.event.inputs.force_update == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🎮 自动更新 GameLove hosts 文件 - $(date '+%Y-%m-%d %H:%M:%S')"
        git push origin main
    
    - name: 获取当前时间
      id: date
      if: steps.check_changes.outputs.has_changes == 'true' || github.event.inputs.force_update == 'true'
      run: echo "date=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

    - name: 创建发布版本
      if: steps.check_changes.outputs.has_changes == 'true' || github.event.inputs.force_update == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: GameLove Hosts v${{ github.run_number }}
        body: |
          🎮 GameLove 游戏平台网络优化 - 自动更新
          
          📅 更新时间: ${{ steps.date.outputs.date }}
          🔄 更新方式: 自动更新
          
          ## 📥 快速使用
          
          ### 方法一：直接下载
          ```bash
          # Windows (管理员权限)
          curl -o C:\Windows\System32\drivers\etc\hosts https://raw.githubusercontent.com/${{ github.repository }}/main/hosts
          
          # Linux/Mac
          sudo curl -o /etc/hosts https://raw.githubusercontent.com/${{ github.repository }}/main/hosts
          ```
          
          ### 方法二：SwitchHosts
          - URL: `https://raw.githubusercontent.com/${{ github.repository }}/main/hosts`
          - 自动刷新: 1小时
          
          ## 🎯 支持平台
          - Steam
          - Epic Games
          - Origin (EA)
          - Uplay (Ubisoft)
          - Battle.net (Blizzard)
          - GOG
          - Rockstar Games
          
          让你"爱"上游戏，解决访问慢、连接超时的问题！
        draft: false
        prerelease: false
